apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: siraone-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
    - siraone.ca
    secretName: siraone-tls-secret  # Reference your SSL certificate here
  rules:
  - host: siraone.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: siraone-service
            port:
              number: 80