apiVersion: v1
kind: Service
metadata:
  name: siraone-service
spec:
  type: LoadBalancer
  selector:
    app: siraone
  ports:
  - name: http       # Unique name for the first port
    protocol: TCP
    port: 80         # External port
    targetPort: 80   # Pod container port
  - name: api        # Unique name for the second port
    protocol: TCP
    port: 5001       # External port
    targetPort: 5001 # Pod container port